-- 002_rls.sql
-- No Supabase, isso habilitava RLS com policies baseadas em auth.role().
-- No Neon (Postgres puro + Managed Better Auth), a autorização acontece
-- inteiramente na camada de aplicação: toda rota passa por auth.middleware()
-- (ver proxy.ts) antes de chegar nas rotas que usam a role dona do banco
-- (DATABASE_URL), que já ignora RLS por padrão. Não há RLS a configurar
-- aqui -- arquivo mantido só pra preservar a numeração das migrations.
